name: Upgrde Sandwich
on:
  workflow_dispatch:
    inputs:
      sandwich_version:
        description: 'Sandwich version'
        required: true
        default: '0.0.0'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  upgrade_sandwich:
    runs-on: ubuntu-latest

    steps:
      - name: Success
        run: echo '${{ github.event.inputs.sandwich_version }}'
